language: node_js
env:
  global:
    - GH_REF: github.com/w3c/apa.git
    
git:
  depth: 3
  
branches:
  only:
    main

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/apa.git
  - cd apa
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/fast/index.html -o fast/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/captcha/index.html -o captcha/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/media-accessibility-reqs/index.html -o media-accessibility-reqs/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/payment-accessibility-reqs/index.html -o payment-accessibility-reqs/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/xaur/index.html -o xaur/index.html -f  --retry 3
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/apa/main/raur/index.html -o raur/index.html -f  --retry 3
  - cp ../../w3c/apa/fast/checklist.html fast/checklist.html

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
